name: 'Run as user'
description: 'Runs a set of commands as another user, in their shell environment'
inputs:
  commands:
    description: 'Commands to run'
    required: true
  user:
    description: 'User in whose shell environment these commands are executed'
    required: true
  shell:
    description: 'Which shell to use; bash by default'
    required: true
    default: 'bash'
  keyname:
    description: 'Filename for SSH key pair'
    required: false
    default: 'rua_sshkey'

runs:
  using: "composite"
  steps:
    - run: |
        if [[ ! -e ${{ inputs.keyname }} ]]; then
          ssh-keygen -b 1024 -t rsa -f "${{ inputs.keyname }}" -q -N ""
        fi

        HOME_DIR=$(eval echo "~${{ inputs.user }}") ; \
        GROUP=$(id -gn ${{ inputs.user }}) ;\
        SSH_DIR="$HOME_DIR/.ssh" ; \
        sudo mkdir -p $SSH_DIR ; \
        sudo chmod 700 $SSH_DIR ; \
        sudo chown -R ${{ inputs.user }}:${GROUP} $SSH_DIR ; \
        # Could add check here to prevent duplication, but not necessary ; \
        cat "${{ inputs.keyname }}.pub" | sudo tee -a $SSH_DIR/authorized_keys > /dev/null ; \
        sudo chmod 644 $SSH_DIR/authorized_keys
      shell: bash
    - run: |
        ssh -o StrictHostKeyChecking=no -i "${{ inputs.keyname }}" ${{ inputs.user }}@localhost ${{ inputs.shell }} -c \"'${{ inputs.commands }}'\"
      shell: bash
