name: 'Run as user'
description: 'Runs a set of commands as another user, in their shell environment'
inputs:
  commands:
    description: 'Commands to run'
    required: true
  user:
    description: 'User in whose shell environment these commands are executed'
    required: true
  shell:
    description: 'Which shell to use; bash by default'
    required: true
    default: 'bash'
  keyname:
    description: 'Filename for SSH key pair'
    required: false
    default: 'rua_sshkey'

runs:
  using: "composite"
  steps:
    - run: |
        sudo python generate-key.py "${{ inputs.keyname }}" ${{ inputs.user }}
        # Give runner access to generated SSH key
        sudo chown $USER:$USER "${{ inputs.keyname }}"
      shell: bash
    - run: |
        ssh -o StrictHostKeyChecking=no -i "${{ inputs.keyname }}" ${{ inputs.user }}@localhost ${{ inputs.shell }} -c \"'${{ inputs.commands }}'\"
      shell: bash
