name: 'Run as user'
description: 'Runs a set of commands as another user, in their shell environment'
inputs:
  commands:
    description: 'Commands to run'
    required: true
  user:
    description: 'User in whose shell environment these commands are executed'
    required: true
  shell:
    description: 'Which shell to use; bash by default'
    required: true
    default: 'bash'
  keyname:
    description: 'Filename root for SSH key pair'
    required: false
    default: 'rua_sshkey'

runs:
  using: "composite"
  steps:
    - run: |
        stamp_file=".${{ inputs.user }}-${{ inputs.keyname }}" ; \
        if [ ! -e ${{ inputs.keyname }} ]; then
          ssh-keygen -b 2048 -t rsa -f ${{ inputs.keyname }} -q -N "" ; \
        fi; \
        if [ ! -e $stamp_file ]; then
          HOME_DIR=$(eval echo "~${{ inputs.user }}") ; \
          SSH_DIR=$HOME_DIR/.ssh ; \
          sudo mkdir -p $SSH_DIR ; \
          sudo cat ${{ inputs.keyname }}.pub >> $SSH_DIR/authorized_keys ; \
          GROUP=$(id -gn ${{ inputs.user }}) ;\
          sudo chown -R ${{ inputs.user }}:${GROUP} $SSH_DIR
          touch $stamp_file
        fi
      shell: bash
    - run: |
        ssh -o StrictHostKeyChecking=no -i ${{ inputs.keyname }} ${{ inputs.user }}@localhost ${{ inputs.shell }} -c \"'${{ inputs.commands }}'\"
      shell: bash
