name: Test

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      TEST_USER: test-user
      TEST_USER2: another-user
    steps:
      - uses: actions/checkout@v4

      - name: Create user
        run: |
          sudo useradd -m $TEST_USER
          HOMEDIR=$( getent passwd "$TEST_USER" | cut -d: -f6 )
          echo $HOMEDIR
          echo "export ENVVAR='xyz'" | sudo tee $HOMEDIR/.bashrc
          sudo useradd -m $TEST_USER2

      - name: Test executing commands as user
        uses: ./
        with:
          commands: |
            whoami
            ls -al
            cat ~/.bashrc
            echo $HOME
            [[ "$ENVVAR" == "xyz" ]]
          user: $TEST_USER
          shell: bash

      - name: Test second execution
        uses: ./
        with:
          commands: |
            [[ $( whoami ) == "test-user" ]]
          user: $TEST_USER
          shell: bash

      - name: Test third execution, different user
        uses: ./
        with:
          commands: |
            [[ $( whoami ) == "another-user" ]]
          user: $TEST_USER2
          shell: bash

      - name: Original user, different key
        uses: ./
        with:
          commands: |
            [[ $( whoami ) == "test-user" ]]
          user: $TEST_USER
          shell: bash
          keyname: another_key

      - name: Original user, original key
        uses: ./
        with:
          commands: |
            [[ $( whoami ) == "test-user" ]]
          user: $TEST_USER
          shell: bash
